version: '3.3'
services:
  php:
    container_name: php
    build:
      context: ./php
      dockerfile: Dockerfile
    ports:
      - '9000:9000'
    volumes:
      - ./app:/var/www/html/symfony_docker-mysql
    depends_on:
      - database

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/html/symfony_docker-mysql
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database

  database:
    container_name: db-symfony
    image: mysql
    #command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ROOT_PASSWORD
      MYSQL_DATABASE: symfony_docker
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '9906:3306'
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    container_name: phpmyadmin-symfony
    links:
     - database
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: ROOT_PASSWORD
    restart: always
    ports:
      - 9001:80
    depends_on:
      - database
